version: "3"

dotenv: [".env"]

tasks:
  pull:
    - git submodule update --init --recursive

  install:
    - cd protocol && yarn
    - cd frontend-v1 && yarn

  frontend:
    dir: frontend-v1
    cmds:
      - yarn {{.CLI_ARGS}}

  protocol:
    dir: protocol
    cmds:
      - yarn {{.CLI_ARGS}}

  develop:
    cmds:
      - task localhost:node &
      - task localhost:deploy
      - task frontend -- start

includes:
  localhost: ./networks/Localhost.yml
  rinkeby: ./networks/Rinkeby.yml
  mainnet: ./networks/Mainnet.yml
