version: "3"

dotenv: [".env"]

tasks:
  pull:
    - git submodule update --init --recursive

  install:
    - cd protocol && yarn
    - cd frontend-v1 && yarn

  develop:
    deps: [run-testnode, deploy-and-start]
    cmds:
      - echo "Closed!"

  # ↓ helper scripts

  run-testnode: task localhost:node

  deploy-and-start: task localhost:deploy && task frontend -- start

  frontend:
    dir: frontend-v1
    cmds:
      - yarn {{.CLI_ARGS}}

  protocol:
    dir: protocol
    cmds:
      - yarn {{.CLI_ARGS}}

includes:
  localhost: ./networks/Localhost.yml
  rinkeby: ./networks/Rinkeby.yml
  mainnet: ./networks/Mainnet.yml
