version: "3"

tasks:
  build:
    dir: protocol
    cmds:
      - yarn build

  node:
    dir: protocol
    cmds:
      - yarn hardhat node --hostname 0.0.0.0

  deploy:
    dir: protocol
    deps: [build]
    cmds:
      - rm -f deployed.dev.json
      - yarn localhost run scripts/deploy.ts
      - cp deployed.dev.json ../frontend-v1/src/
      - yarn localhost run scripts/demo/all.ts
