version: "3"

tasks:
  compile:
    dir: protocol
    cmds:
      - yarn build

  deploy:
    dir: protocol
    preconditions:
      - sh: test -f ../.env
        msg: "Please create .env on workspace root directory."
    deps: [compile]
    cmds:
      - yarn mainnet run scripts/deploy.ts
      - cp deployed.json ../frontend-v1/src/deployed.dev.json
      - echo "Deployed. Don't forget to publish the package to npm"
